name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build
      run: |
        # Add your build steps here, for example:
        pyinstaller --onefile main.py

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-app
        path: dist/main  # Adjust path if necessary

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0.0  # Update this tag dynamically based on your versioning strategy
        release_name: Release v1.0.0
        body: |
          ## Changes
          - Initial release
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/main  # Adjust path if necessary
        asset_name: main
        asset_content_type: application/octet-stream
