name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile main.py  # Adjust the pyinstaller command as needed
        ls dist  # List the dist directory to verify the output
    - name: Tag the Commit
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git tag -a v1.0.1 -m "Automated release"  # Replace with your desired version
        git push origin v1.0.1
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0.1 
        release_name:  Release v1.0.1
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/main  # Ensure this matches the actual path
        asset_name: main  # The name you want the file to have in the release
        asset_content_type: application/octet-stream
